version: '3.7'

services:
  db:
    image: postgres
    container_name: textsummarizer_api_db
    restart: always
    environment:
      POSTGRES_DB: textsummarizer_api_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  db: